categories = {
    '.*ALL DAY MINI MART LLC.*': 'Grocery',
    '.*YOUTUBEPREMIUM.*': 'Subscription',
    '.*WOOD AND FOOD REST.*': 'Lunch',
    '.*EMIRATES LEIS ENBD BLD.*': 'Coffee',
    '.*Donaza restaurant llc.*': 'Lunch',
    '.*COSTA COFFEE.*': 'Coffee',
    '.*YOUSICIAN.*': 'Subscription',
    '.*BERTS RESTAURANT BR.*': 'Restaurants',
    '.*PERFETTO TRADING COMPA.*': 'Grocery',
    '.*Amazon.ae.*': 'Amazon',
    '.*DU AUTOPAYMENT.*': 'Internet',
    '.*SPOTIFY.*': 'Subscription',
    '.*Insta Shop DMCC.*': 'Grocery',
    '.*FIVE CROWNS.*': 'Lunch',
    '.*GOLDENFROGI.*': 'Subscription',
    '.*GOOGLE*ADS.*': 'Other',
    '.*CAFU.*': 'Car',
    '.*GEMS FOUNDERS SCHOOL.*': 'Kids Education',
    '.*GEMS SCHOOL.*': 'Kids Education',
    '.*INSTASHOP.*': 'Grocery',
    '.*H AND M ALSHAYA.*': 'Shopping',
    '.*TALABAT.*': 'Restaurants',
    '.*Careem Networks.*': 'Taxi',
    '.*LIWA TRADING ENTERPRIS.*': 'Shopping',
    '.*SHAKIROVNA.*': 'Beauty',
    '.*HEALTHCARE.*': 'Healthcare',
    '.*PHARMACY.*': 'Healthcare',
    '.*Mall of the Emirates.*': 'Shopping',
    '.*EMIRATES LEISURE.*': 'Coffee',
    '.*TWO BALLET DANCE.*': 'Kids Education',
    '.*ORGANIC FOODS .*': 'Grocery',
    '.*FIRSTCRY RETAIL DWC.*': 'Shopping',
    '.*CHOITHRAMS.*': 'Grocery',
    '.*TCO DAMAS ASSOCIATES.*': 'Shopping',
    '.*MICHAEL KORS.*': 'Shopping',
    '.*Careem Pay.*': 'Taxi',
    '.*APPLE STORE.*': 'Shopping',
    '.*LRIL-CENTREPOINT.*': 'Shopping',
    '.*DUBAI TAXI.*': 'Taxi',
    '.*SERVICE SOUK DMCC.*': 'Services',
    '.*ASOS.COM.*': 'Shopping',
    '.*ALSHAYA.*': 'Shopping',
    '.*allright.*': 'Kids Education',
    '.*AL SHAYA.*': 'Shopping',
    '.*ITUNES.*': 'Subscription',
    '.*CARIBOU COFFEE.*': 'Coffee',
    '.*PTB FARZANATRADING.*': 'Grocery',
    '.*ASWAAQ MART.*': 'Grocery',
    '.*PLANET TERRA.*': 'Restaurants',
    '.*PIZZA HUT.*': 'Restaurants',
    '.*IKEA.*': 'Shopping',
    '.*IHERB.*': 'Healthcare',
    '.*LANDMARK RETAIL INVEST.*': 'Shopping',
    '.*ShakirovnaSaloon.*': 'Beauty',
    '.*CARS TAXI.*': 'Taxi',
    '.*ALLIED ENTERPRISES LLC.*': 'Shopping',
    '.*Insta Shop.*': 'Grocery',
    '.*AWS EMEA.*': 'Programming',
    '.*GOOGLE*ADS2036270393.*': 'Remove',
    '.*ZOOL BARBER SHOP.*': 'Beauty',
    '.*SmartDXBGov-DEWA.*': 'DEWA',
    '.*Yandex.Music.*': 'Subscription',
    '.*WINDMILL GENERAL.*': 'Alkomarket',
    '.*TODO.*': 'Shopping',

}
